audiofile/__init__.py
tests/test_audiofile.py

The current implementation was using `sox` for getting the duration and number of samples for MP3 files, if `sox` comes with MP3 support. Unfortunately, `sox` reports slightly longer signals then we actually get after loading them with `audiofile.read`.
This PR introduces corresponding tests to spot the error and fixes it by not using `sox` for `duration` and `samples`.

Fix mp3 number of samples

---

audiofile.py
tests/test_audiofile.py

I switched from downloading example videos from `https://sample-videos.com` to audio files from `https://dl.espressif.com/dl/audio/` as the first URL do no longer provide the service.
I also catch `SoxiError` as this can be thrown as well as `SoxError` inside `audiofile.read`

Fix tests and check for Soxi error

---

README.rst
docs/index.rst
docs/installation.rst
docs/usage.rst

This simplifies the README and structure of the documentation by moving the installation and usage section out of the README.

DOC: split install and usage from readme

---

README.rst

The documentation is now hosted as Github pages

DOC: update doc badge in readme

---

docs/conf.py

Removes `$ ` from bash prompt and handles also ipython prompts.

DOC: remove prompt from copy button output

---

audiofile/__init__.py
audiofile/core/info.py
audiofile/core/io.py
audiofile/core/utils.py
docs/api.rst
tests/test_audiofile.py

Adds:
* `audiofile.bit_depth`
Fixes:
* `audiofile.write` docstring for precision
It's a little bit unfortunate that I would like to use `bit_depth` as it is more precise what kind of precision we mean, but on the other hand we have the `precision` argument to `audiofile.write`. So, I'm not sure how to bet solve this.
Another question is if we should return an integer or a string. I'm returning now an integer, but I'm not sure if this is correct for `GSM610` and `G721_32`.

Add audiofile.bit_depth

---

docs/usage.rst

Adds an example to the usage section for the new `bit_depth()` function.

DOC: add bit_depth to usage

---

audiofile/core/convert.py
audiofile/core/info.py
audiofile/core/io.py
setup.cfg

Closes #28.
It now uses `audeer.safe_path` for every function that handles files.
We haven't done this before, because `audeer` was not available at the beginning.

Handle pathes with ~ and ..

---

audiofile/core/io.py
tests/test_audiofile.py

Closes #32.
This allows a user to specify `duration=0.0` when using `audiofile.read()`.
It also adds new tests for it.

Fix audiofile.read for duration=0.0

---

docs/benchmark/requirements.txt
docs/benchmark/requirements.txt.lock

* `pip` should not be part of the requirement file
* the `requirements.txt.lock` was not using the PyPI public URL

DOC: cleanup requirement files for benchmark

---

audiofile/core/io.py

Closes #36 
We were indeed setting the `dtype` argument directly for `soundfile` to `float32` without documenting it.
This pull requests adds `dtype` to the arguments of `audiofile.read()` and allows the user to change it.

Add dtype as keyword argument to audiofile.read()

---

README.rst
docs/index.rst

* Add a development section to the TOC as we do in other projects
* Update code example in README to use `import audiofile` instead of `import audiofile as af`
* Mention `soundfile` in README
* Mention that duration and samples match for decoded files in README

DOC: update TOC and be more verbose on README

---

audiofile/core/info.py
docs/api.rst
docs/conf.py

Use the `sphinx.ext.autosummary` extension to show an overview at the top of the API page.

DOC: add summary of functions at top of API page

---

audiofile/core/io.py

In `read` and `write` we showed notes that OGG is not working under Ubuntu 16.04.
As Ubuntu 16.04 has reached its end of life we remove these notes here.

DOC: remove notes regarding Ubuntu 16.04

---

audiofile/core/io.py
tests/test_audiofile.py

* Changes `SystemExit` to `RuntimeError` when `audiofile.write()` is called with a non-supported combination of channels and format or a wrong bit depth
* Added the `RuntimeError` to the docs

write() raises RuntimeError instead of SystemExit

---

audiofile/core/io.py
tests/test_audiofile.py

In `audiofile.write()` we allowed for `precision` instead of `bit_depth` and for ung `'16bit'` instead of `16` for the `bit_depth` argument. Both were marked as deprecated and removed in versions >=0.5.0.
As the next release will be 1.0.0, we can remove the deprecated code.

Remove deprecated precision argument from write()

---

docs/usage.rst

As we have switched in the example in the README from
```python
import audiofile as af
```
to
```python
import audiofile
```
we should do the same in the usage section.

DOC: use audiofile instead of af in usage section

---

audiofile/core/utils.py

As we need lower case file extensions, we implement `audiofile.core.utils.file_extension()`.
This does now use `audeer.file_extension().lower()`, to make sure it uses our ground truth implementation in `audeer`.

Use audeer.file_extension()

---

docs/installation.rst

Add the suggestion to install sox with MP3 support to the install section of the docs.

DOC: suggest to install sox with MP3 support

---

audiofile/core/convert.py
audiofile/core/info.py
audiofile/core/io.py
audiofile/core/utils.py
tests/test_audiofile.py

This extends our error handling for empty and broken files:
* added additional checks for the empty file case
* added tests for broken files
I differentiate between empty and broken files as the empty ones still contain a valid number of channels, samples and sampling rate.
For the broken files we now always raise a `RuntimeError` with the same error message as `soundfile` would raise for broken SND files.
E.g.
```python
>>> open('broken.wav', 'w').close()
>>> audiofile.duration('broken.wav')
...
RuntimeError: Error opening '/home/audeering.local/hwierstorf/git/audeering/audiofile/broken.wav': File contains data in an unknown format.
>>> open('broken.mp3', 'w').close()
>>> audiofile.duration('broken.mp3')
...
RuntimeError: Error opening …
```

Raise RuntimeError for broken files

---

tests/test_audiofile.py

As a first step before tackling #62 I added a test to make sure we raise the expected error messages when the file does not exists. As the main motivation behind `audiofile` was to be as fast as possible, we do not have manual checks for the existence of files, which means the error message raised in the case of a missing file depends on the library that is used for reading the file, leading to different errors for different file types.
As returned error types are part of the API they should not change when we tackle #62.

TST: test for missing files

---

.github/workflows/test.yml

As we are no longer able to install `sox` under Windows with [chocolatey](https://chocolatey.org) we switch to use `conda` - compare [sox-feedstock](https://github.com/conda-forge/sox-feedstock). `conda` works on all platforms, so I extended the install method for `sox` to Linux and macOS as well.
`mediainfo` is not available under `conda`, only [pymediainfo](https://github.com/sbraz/pymediainfo) - compare [pymediainfo-feedstock](https://github.com/conda-forge/pymediainfo-feedstock) - which does not provide the needed commandline interface of `mediainfo-cli`. Hence I decided to limit `conda` to install `sox` for now.

TST: fix installation of sox under Windows

---

docs/benchmark.rst

There was a typo in the instructions on how to run the benchmark as the file for creating the audio files is called https://github.com/audeering/audiofile/blob/master/docs/benchmark/generate_audio.sh

DOC: fix typo in benchmark instructions

---

.github/workflows/test.yml

This introduces the key `tasks` to the matrix definition in `.github/workflows/test.yml` to make it easier to separate tests for code and documentation. This has the advantage that we can use the same Ubuntu version in tests and docs as we now can use the `tasks` key to check if we should build the docs. I also updated the code that only the task specific requirements are installed.
The tasks key is then also visible when the Actions are executed:

TST: separate test for building documentation

---

audiofile/core/convert.py
audiofile/core/info.py
audiofile/core/io.py
tests/test_audiofile.py

Before in the docs we always stated:
I updated this to
in all relevbant docstrings.
We did already tested for missing files in the tests, but before, `sox` and `ffmpeg`/`mediainfo` were raising `OSError` when a file was missing. Some days ago I voted not to change this, but as we never stated in the documentation that they should raise an `OSError` I think it makes more sense to fix this and always return the desired `RuntimeError` as done in this pull request.
In addition, I added all the relevant tests for `audiofile.convert_to_wav()` as well, as we didn't test the error there before.

Make sure we raise RuntimeError for broken files

---

tests/test_audiofile.py

Closes #51.
Before we were using `sox` to create MP3 files, but `sox` does not support MP3 in the Windows runners (and we will remove `sox` altogether from the tests in upcoming pull requests). I switch to `ffmpeg` here and re-enable the tests under Windows.
I also removed the magnitude test as we did not really check if `audiofile` works there, but the MP3 encoder, which is not needed (and fails for the current `ffmpeg` settings).

TST: enable MP3 tests under Windows

---

tests/test_audiofile.py

This removes the necessity of having `sox` installed for executing the tests.
It is achieved by using `soundfile` instead to compare against.

TST: don't require sox in tests

---

audiofile/core/convert.py
audiofile/core/io.py

This applies our changes to the description of the `RunTimeError` also to `audiofile.convert_to_wav()`.

DOC: fix error description for convert_to_wav()

---

.github/workflows/test.yml
audiofile/core/convert.py
audiofile/core/info.py
audiofile/core/sox.py
audiofile/core/utils.py
docs/installation.rst

Closes #62 
This adjusts the code so that `ffmpeg` or `mediainfo` is used if the `sox` binary cannot be found instead of raising an `FileNotFoundError` as before.
It also makes sure that we don't get a warning printed to screen that `sox` is missing.
This is tested by not installing the `sox` binary when building the documentation, which would fail if a warning is given.
In addition, the tests under Python 3.8 are extended to be run with and without `sox` installed:
The installation instructions now mention that `sox` is only optional:

Allow sox binary to be missing

---

tests/test_audiofile.py

Closes #23 
This re-enables the duration test for MP3 files with 2 channels and a sampling rate of 48000 Hz.
I guess the test failed before not due to `audiofile`, but due to the creation of the MP3 files with `sox`, which we changed to `ffmpeg` in https://github.com/audeering/audiofile/pull/72

TST: test MP3 file duration in all cases

---

LICENSE
setup.cfg

Sets second year in LICENSE file to `present` and adds @frankenjoe and @ChristianGeng as authors.

Update license year and authors

---

audiofile/core/convert.py
audiofile/core/info.py
audiofile/core/io.py
audiofile/core/utils.py
tests/test_audiofile.py

Closes #30 
When the `ffmpeg` or `mediainfo` binaries are missing we have been raising a `FileNotFoundError` before, but this behavior was not documented and not tested.
This pull request extends the docstrings accordingly, depending on if `ffmpeg` or `mediainfo` is needed:
In addition, it adds a custom error message to solve #30:
```
E               FileNotFoundError: ffmpeg cannot be found.
E               Please make sure it is installed.
E               For further instructions visit: https://audeering.github.io/audiofile/installation.html
```
And adds tests for the missing binaries.

Custom FileNotFoundError for missing binaries

---

.github/workflows/test.yml

Adjusts the tests to use `main` as default branch name.

TST: set default branch name to main

---

.github/workflows/flake8.yml
.pre-commit-config.yaml
CONTRIBUTING.rst
docs/benchmark/benchmark_info.py
docs/benchmark/benchmark_read.py
docs/benchmark/loaders.py
docs/benchmark/plot.py
docs/benchmark/utils.py
setup.cfg
tests/requirements.txt
tests/test_audiofile.py

This uses [pre-commit](https://pre-commit.com) instead of `pytest` to execute the `flake8` tests.
It also fixes a few flake8 issues and adds a coding convention section to CONTRIBUTING.

TST: use pre-commit for flake8 checks

---

.github/workflows/test.yml

This uses `micromamba` which is a faster alternative for `conda` from https://github.com/mamba-org/mamba.
It can still install all the `conda` packages and use the `conda` repos like `conda-forge`.
The main motivation for this switch are:
* we got an error with `conda` for whatever reason at https://github.com/audeering/audiofile/actions/runs/4004437981/jobs/6873558679
* the time for setting up `sox` with `conda` is 150 s, with `micromamba` it is 40 s in the first run and 8 s when running a second time in the same branch due to caching
I now use `micromamba` also to handle the case where we don't need to install `sox` to create a virtual environment with the desired Python version replacing `actions/setup-python@v4` as it is not slower and makes the code easier to write and to understand.

CI: use micromamba instead of conda for sox

---

audiofile/core/info.py
audiofile/core/io.py
tests/test_audiofile.py

The goal of this pull request is that the following two commands will always result in the same outfile.
```python
audiofile.convert_to_wav(infile, outfile)
```
```python
signal, sampling_rate = audiofile.read(infile)
audiofile.write(outfile, signal, sampling_rate)
```
---
This was not the case before. E.g. executing `audiofile.convert_to_wav()` on a SPH file from LDC could lead to the following WAV file (compare https://github.com/audeering/audb/issues/161):
```bash
$ soxi sw_10001.wav
Input File     : 'sw_10001.wav'
Channels       : 2
Sample Rate    : 8000
Precision      : 14-bit
Duration       : 00:05:00.00 = 2400000 samples ~ 22500 CDDA sectors
File Size      : 4.80M
Bit Rate       : 128k
Sample Encoding: 8-bit u-law
```
whereas a conversion by using `audiofile.read()` and …

Ensure convert_to_wav() creates desired WAV file

---

audiofile/core/conftest.py
audiofile/core/info.py
audiofile/core/io.py
setup.cfg
tests/requirements.txt

Closes #95
This adds examples to all docstrings.
It adds a `conftest.py` file to `audiofile/core/` to create `mono.wav`, `stereo.wav`, and `stereo.flac` files before the doctests are executed and remove them afterwards.

DOC: add docstring examples

---

audiofile/core/io.py
tests/test_audiofile.py

Closes https://github.com/audeering/audiofile/issues/102
This let `audiofile.convert_to_wav(infile, outfile)` return the absolute path to `outfile`.

Return WAV path in convert_to_path()

---

audiofile/core/io.py
tests/test_audiofile.py

Closes #103 
This extends `audiofile.convert_to_wav()` by changing the `outfile` argument to `outfile=None` which then uses the same path as `infile`, but replaces the file extension with WAV.
It also adds the `overwrite` argument, to handle cases where the name of the resulting `outfile` is identical to the `infile`.

Allow outfile=None in convert_to_wav()

---

.github/workflows/test.yml

~~Makes sure to install `mediainfo` with `brew` using `--cask` as mentioned in~~
Using `--cask` did not work, but it seems the package is now simply called [media-info](https://formulae.brew.sh/formula/media-info), and works as expected.

CI: fix installation of mediainfo on MacOS

---

audiofile/core/utils.py

In windows, the path of a file in a network share start with `\\`. Using `shlex.split` here:
https://github.com/audeering/audiofile/blob/e58253ca7c9a8495bb8a02aba14cc5f95fed83c0/audiofile/core/utils.py#L53
remove a `\` so the file is not found.
Example path: `\\my_share\audio\test.mka` is converted in `\my_share\audio\test.mka`.
This should fix it.

Fix: support for non SND files on Windows network shares

---

audiofile/core/info.py

In #111 we removed the splitting of bash command lines by `shlex.split()` as it does not work under Windows in all cases, but we forgot to adjust the commands in `audiofile/core/info.py`, which is added by this pull request.

Fix: calling mediainfo in the info sub-module

---

audiofile/core/io.py
docs/conf.py
docs/requirements.txt
docs/usage.rst
tests/requirements.txt

Closes #110 
This extends the usage documentation and the docstring example of `audiofile.read()` to show how to resample and remix a file/signal with `audresample`.
I also adjusted the output of some of the existing sub-sections:

DOC: add audresample resample()/remix() examples

---

audiofile/core/io.py
tests/test_audiofile.py

Closes #116 
This adds a test to check that the `normalize` argument in `audiofile.convert_to_wav()` is passed on to `audiofile.write()`
and fixes the implementation.

Fix: make sure normalize is applied in convert_to_wav()

---

tests/test_audiofile.py

Adds a test to check that negative `duration` and `offset` arguments also work for MP3 and MP4 files.

TST: test non SND files for negative durations

---

.github/workflows/test.yml

As stated in https://github.com/mamba-org/provision-with-micromamba the GitHub Action `provision-with-micromamba` is deprecated and replaced by [mamba-org/setup-micromamba](https://github.com/mamba-org/setup-micromamba).

CI: use setup-micromamba GitHub Action

---

.github/workflows/test.yml
pyproject.toml

Python 3.7 has reached its [end of life](https://endoflife.date/python) at 2023/06/27, so we remove support for it.

Remove support for Python 3.7

---

audiofile/core/io.py
audiofile/core/utils.py
tests/test_audiofile.py

Related to https://github.com/audeering/audinterface/issues/123
This changes how the `offset` and `duration` values of `audiofile.read()` and `audiofile.convert_to_wav()` are rounded towards samples when not given as samples.
Before those values were evenly rounded (`int(round(...))`) for non SND files (e.g. MP3, MP4), but upwardly rounded (`int(np.ceil(...))`) for SND files (WAV, FLAC, OGG). See https://en.wikipedia.org/wiki/Rounding for a discussion of the used terminology.
Now they are **evenly rounded in both cases**. This means for a sampling rate of 10 Hz, a duration of 0.11 s would return a single sample, whereas before it would return 2 samples. We now return 2 samples for a duration of 0.15 s:
```python
>>> sampling_rate = 10  # Hz
>>> duration = 0.11  # s
>>> int(round(duration …
```

Evenly round offset/duration to samples

---

docs/requirements.txt

`jupyter-sphinx` has a bug and does not specify `ipykernel` as its dependency.

DOC: add ipykernel as dependency

---

audiofile/__init__.py

`pkg_resources` is deprecated and since Python 3.8 we can use `importlib.metadata` to get the version of a package.

Use importlib.metadata instead of pkg_resources

---

audiofile/core/utils.py

This speeds up `audiofile.read()` and all the functions from `audiofile.core.info` by not calling `audeer.safe_path()` when getting the file extension of a file, as we called `audeer.safe_path(file)` before.

Avoid extra call of safe_path in file_extension()

---

docs/benchmark/README.md
docs/benchmark/benchmark_info.py
docs/benchmark/benchmark_read.py
docs/benchmark/install_dependencies.sh
docs/benchmark/utils.py

This documents how to prepare and execute the benchmark. And updates the benchmark code to avoid deprecation warnings and add a hint if the audio files for the benchmark are missing.
**NOTE**: this is also documented in the online documentation at https://audeering.github.io/audiofile/benchmark.html#running-the-benchmark, but it might be that a user does not find it when trying to run the benchmark locally.

DOC: add README for benchmark code

---

README.rst
audiofile/core/io.py
audiofile/core/utils.py
docs/usage.rst
tests/test_audiofile.py

After introducing read support for MP3 file with `libsndfile` in #145, this pull requests uses `libsndfile` to write MP3 files.
The most important part is that we add `'mp3'` as supported part to `MAX_CHANNELS` to not get an error when trying to write it. Otherwise, we just need to pass it on to `soundfile` as with reading.
So the main part of this pull request is updating the documentation and simplifying the tests as we no longer need ffmpeg` to create MP3 files in the tests.

Add support for writing to MP3 files

---

pyproject.toml

`audiofile` uses `audmath.samples()` under the hood, which was only introduced in `audmath` v1.3.0, so we need to require at least that version of `audmath`.

Depend on audmath>=1.3.0

---

audiofile/core/io.py

We do not only allow for two dimensional signals in `audiofile.write()`, but also for single dimensional if only a single channel is given.

DOC: fix supported signal shapes in write()

---

.github/workflows/doc.yml
.github/workflows/linter.yml
.github/workflows/publish.yml
.github/workflows/test.yml

Update CI Actions to their latest versions, and use Python 3.10 as default in CI jobs.

CI: update Actions, Python 3.10 as default
